# This docker-compose file can be used to bring up an example instance of oauth2-proxy
# using the new alpha config options.
# This config is used alongside the standard docker-compose.yaml for OAuth2-Proxy
#
# This can either be created using docker-compose
#    docker-compose -f docker-compose.yaml -f docker-compose-alpha-config.yaml up -d
# Or:
#    make alpha-config-up
#
# Access http://localhost:4180 to initiate a login cycle
version: '3.0'
services:
  oauth2-proxy:
    command: --config /oauth2-proxy.cfg --alpha-config /oauth2-proxy-alpha-config.yaml
    volumes:
      - "./oauth2-proxy-alpha-config.cfg:/oauth2-proxy.cfg"
      - "./oauth2-proxy-alpha-config.yaml:/oauth2-proxy-alpha-config.yaml"
