upstreamconfig:
  upstreams:
    - id: httpbin
      path: /
      uri: http://httpbin
templates:
  additionalCss:
    - https://media.douglas.de/hybr/lib/css/oauthDglecom.css
  customLogo: https://www.tempelhofer-hafen.com/fileadmin/user_upload/GLOBAL/brand_stores/logos/douglas.jpg
  displayLoginForm: true
injectResponseHeaders:
  - name: X-Forwarded-Groups
    values:
    - claim: groups
  - name: X-Forwarded-User
    values:
    - claim: user
  - name: X-Forwarded-Email
    values:
    - claim: email
  - name: X-Forwarded-Provider
    values:
    - claim: provider
providers:
- provider: oidc
  id: dex
  name: "@dexexample.com"
  clientSecret: b2F1dGgyLXByb3h5LWNsaWVudC1zZWNyZXQK
  clientID: oauth2-proxy
  oidcConfig:
    issuerURL: http://dex.localhost:4190/dex
- provider: oidc
  id: keycloak
  name: "@keycloakexample.com"
  clientSecret: 72341b6d-7065-4518-a0e4-50ee15025608
  clientID: oauth2-proxy
  oidcConfig:
    issuerURL: http://keycloak.localtest.me:9080/auth/realms/master
server:
  BindAddress: 0.0.0.0:4180
  SecureBindAddress: ""
  TLS: null